In [4]:
import numpy as np# image  to array
from PIL import Image#image read
img=Image.open("/content/cf7255ae7344ce44e62f784fe160ca0d.jpg")
a=np.array(img).reshape(-1,1)
a

array([[ 63],
       [ 52],
       [ 34],
       ...,
       [124],
       [123],
       [ 93]], dtype=uint8)

In [7]:
s=np.array([[1,2,3],[4,5,6]])
s# rows=2 ,columns =3

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:

t=s.reshape(3,2)
t# row=3,columns=2  2d array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
d=s.reshape(-1,1)
d # 1d array


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [11]:
import pandas as pd # dataset -read,write and also cleaning
data=pd.read_csv("/content/Country (1).csv")
data


,CountryCode,ShortName,TableName,LongName,Alpha2Code,CurrencyUnit,SpecialNotes,Region,IncomeGroup,Wb2Code,...,GovernmentAccountingConcept,ImfDataDisseminationStandard,LatestPopulationCensus,LatestHouseholdSurvey,SourceOfMostRecentIncomeAndExpenditureData,VitalRegistrationComplete,LatestAgriculturalCensus,LatestIndustrialData,LatestTradeData,LatestWaterWithdrawalData
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2013.0,2000.0
1,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2011.0,2013.0,2006.0
2,DZA,Algeria,Algeria,People's Democratic Republic of Algeria,DZ,Algerian dinar,NaN,Middle East & North Africa,Upper middle income,DZ,...,Budgetary central government,General Data Dissemination System (GDDS),2008,"Multiple Indicator Cluster Survey (MICS), 2012","Integrated household survey (IHS), 1995",NaN,NaN,2010.0,2013.0,2001.0
3,ASM,American Samoa,American Samoa,American Samoa,AS,U.S. dollar,NaN,East Asia & Pacific,Upper middle income,AS,...,NaN,NaN,2010,NaN,NaN,Yes,2007,NaN,NaN,NaN
4,ADO,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,WBG,West Bank and Gaza,West Bank and Gaza,West Bank and Gaza,PS,Israeli new shekel,The new base year is 2004.,Middle East & North Africa,Lower middle income,GZ,...,Budgetary central government,Special Data Dissemination Standard (SDDS),2007,"Multiple Indicator Cluster Survey (MICS), 2014","Integrated household survey (IHS), 2011",NaN,NaN,2010.0,NaN,2005.0
243,WLD,World,World,World,1W,NaN,World aggregate.,NaN,NaN,1W,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Based on official government statistics and In...,Middle East & North Africa,Lower middle income,RY,...,Budgetary central government,General Data Dissemination System (GDDS),2004,"Demographic and Health Survey (DHS), 2013","Expenditure survey/budget survey (ES/BS), 2005",NaN,NaN,2009.0,2013.0,2005.0
245,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,The new base year is 2010. National accounts d...,Sub-Saharan Africa,Lower middle income,ZM,...,Budgetary central government,General Data Dissemination System (GDDS),2010,"Demographic and Health Survey (DHS), 2013/14","Integrated household survey (IHS), 2010",NaN,2010. Population and Housing Census.,NaN,2013.0,2002.0


In [ ]:
import ollama

while True:
    msg = input("You: ")

    response = ollama.chat(
        model="phi3:mini",
        messages=[
            {"role": "user", "content": msg}
        ]
    )
    print("Bot:", response["message"]["content"])